language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: AFYACKu+JVcRpkhjVgaz/eNYRldMdns5xO+iGmIdtWmEwa9CFrHOavWgYE5Z6PrHgOX8Eo6cW6DE7Mb6hZT7BGeV5mmjYoYx3GZZpU54gumDpf3bBFklkXw6ymXsWi4W3a+Du5MFhlZR2qMxtmVgznSDIHJt6F4gRVMbdCHQz92pKX0FdOzrNJ/uQKHI61KN7fbKv8Sufe0INEq77w13tBKBTka3zkrivYmXf/hN/TVvw5XU3C8kIha9URYGaFQH4dbAiRLhMMq6wxzo6ZPCXKSnecmJjIBPDMuv/n3dmUQBkcw0bFSA6FOBUss35NvG+uc4QzXD3s8h48eUYCsQ4xUx2xLCyTzETl/tsDDnWwxhjRV6szsmWSNjagR/O4VLt506+cbBl55gShsQlcFWnBPsiWLrBBVMgMnDZ2ZTYTScECK9QLaPKIwk6JnJDMXOPvBdsXOXDmq5h37KSB0WBJ1FA1fUiqiknijKl+cBAuerakp0xYQuEZE+WihxIsQ+BQfJN2zsRXry+1p93AMFZxXKys4kCXbzYhDs8aOJtVDNQG+A9B1YGmYjKAAQyhA4VbvW6gKFZ1ucsvtupfh23EgqI2eOOVXvs6VvjIznEeJ6IpevqoxspYPvCNqED7ZFeA8Icq3MkoVKNgORzC5WmUcwJNd84/dXatM+96kLfMc=
